packages:
  - "assets"
  - "cli"
  - "documentation"
  - "eslint-config"
  - "mcp"
  - "website"
  - "wordpress-plugin"
  - "!cli/demo/**"
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true
  esbuild: true
  sharp: true
  unrs-resolver: true
  yarn: true
