import {Args, Command, Flags} from '@oclif/core'
import got from 'got'

import {WordpressDXCommand} from './base.js'

export default class Export extends WordpressDXCommand {
  static args = {
    output: Args.string({default: 'snippets.json', description: 'Output file path'}),
  }
  static description = 'Export CodeSnippets from WordPress to a file'
  static examples = [
    '$ wdx export --output snippets.json',
    '$ wdx export --url http://example.com --user root --password password',
  ]
  static flags = {
    ...WordpressDXCommand.baseFlags,
    format: Flags.string({
      char: 'f',
      default: 'json',
      description: 'Output format (json, yaml, php)',
      options: ['json', 'yaml', 'php'],
    }),
  }

  async run(): Promise<void> {
    const {args, flags} = await this.parse(Export)
    const {format, password, url, user} = flags as {
      format: string
      password: string
      url: string
      user: string
    }
    const {output} = args

    try {
      const endpoint = `${url}/wp-json/code-snippets/v1/snippets`
      const auth = Buffer.from(`${user}:${password}`).toString('base64')

      this.log(`📤 Exporting CodeSnippets from ${url}`)

      const snippets: any = await got
        .get(endpoint, {
          headers: {
            Authorization: `Basic ${auth}`,
          },
        })
        .json()

      let exportData
      switch (format) {
        case 'json': {
          exportData = snippets
          break
        }

        case 'php': {
          exportData = this.formatAsPHP(snippets)
          break
        }

        default: {
          exportData = snippets
        }
      }

      const fs = await import('node:fs/promises')
      await fs.writeFile(output, JSON.stringify(exportData, null, 2))

      this.log(`✅ Exported ${snippets.length} snippet${snippets.length === 1 ? '' : 's'} to ${output}`)
    } catch (error) {
      this.error(`❌ Error exporting snippets: ${(error as Error).message}`)
    }
  }

  private formatAsPHP(snippets: any[]): string {
    let output = `<?php\n/**\n * CodeSnippets Export\n * Generated by wordpress-dx CLI\n */\n\n`
    output += `return [\n`

    for (const snippet of snippets) {
      output += `  '${snippet.name}' => [\n`
      output += `    'code' => <<<PHP\n${snippet.code}\nPHP,\n`
      output += `    'active' => ${snippet.active},\n`
      if (snippet.tags && snippet.tags.length > 0) {
        output += `    'tags' => ${JSON.stringify(snippet.tags)},\n`
      }

      output += `  ],\n`
    }

    output += `];\n`
    return output
  }
}
