#!/usr/bin/env node
// Assembles one edition of the plugin (free or plus) into a staging directory and zips
// it. Both editions are built from the same source tree; see README.md for the split.
//
// Usage: node scripts/build-flavor.cjs <free|plus>
const fs = require('fs')
const path = require('path')
const { execFileSync } = require('child_process')

const flavor = process.argv[2]
if (!['free', 'plus'].includes(flavor)) {
  console.error('Usage: node scripts/build-flavor.cjs <free|plus>')
  process.exit(1)
}

const root = path.resolve(__dirname, '..')
const stageDir = path.join(root, '.build-stage', flavor)
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'))

function run(cmd, args, cwd) {
  execFileSync(cmd, args, { cwd, stdio: 'inherit' })
}

fs.rmSync(stageDir, { recursive: true, force: true })
fs.mkdirSync(stageDir, { recursive: true })

// 1. PHP source: src/Plus/ only ships in the plus edition. Even in the free build,
// this directory must be absent from the artifact, not merely inactive (wordpress.org
// guidelines, see obsidian/Product/WordPress.org Plugin Distribution.md §2-3).
fs.cpSync(path.join(root, 'src'), path.join(stageDir, 'src'), {
  recursive: true,
  filter: (src) => flavor === 'plus' || !src.startsWith(path.join(root, 'src', 'Plus')),
})

// 2. Entry file: strip or keep the marked Plus block, patch the header for plus.
const START = '/* LOOPRESS_PLUS_START */'
const END = '/* LOOPRESS_PLUS_END */'
let entry = fs.readFileSync(path.join(root, 'loopress.php'), 'utf8')
const blockPattern = new RegExp(`[ \\t]*${escapeRegExp(START)}[\\s\\S]*?${escapeRegExp(END)}\\n?`, 'g')

if (flavor === 'free') {
  entry = entry.replace(blockPattern, '')
} else {
  // Keep the code between the markers, drop only the marker comment lines themselves.
  entry = entry.replace(new RegExp(`[ \\t]*${escapeRegExp(START)}\\n`, 'g'), '')
  entry = entry.replace(new RegExp(`[ \\t]*${escapeRegExp(END)}\\n`, 'g'), '')
  entry = entry.replace('Plugin Name: Loopress', 'Plugin Name: Loopress Plus')
  entry = entry.replace(
    ' * Description:',
    ' * Update URI: https://loopress.dev\n * Description:',
  )
}
fs.writeFileSync(path.join(stageDir, 'loopress.php'), entry)

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

// 3. uninstall.php: plus-only, it cleans up wp-content/loopress/ which only the plus
// edition ever creates.
if (flavor === 'plus') {
  fs.copyFileSync(path.join(root, 'uninstall.php'), path.join(stageDir, 'uninstall.php'))
}

// 4. readme.txt: each edition has its own.
fs.copyFileSync(
  flavor === 'plus' ? path.join(root, 'flavors/plus/readme.txt') : path.join(root, 'readme.txt'),
  path.join(stageDir, 'readme.txt'),
)

// 5. composer.json + vendor/: free ships an empty require (autoloader only), plus
// ships the real composer/composer dependency staged and installed fresh.
const rootComposerJson = JSON.parse(fs.readFileSync(path.join(root, 'composer.json'), 'utf8'))
const stageComposerJson =
  flavor === 'free'
    ? { ...rootComposerJson, require: {} }
    : rootComposerJson
delete stageComposerJson['require-dev']
delete stageComposerJson.scripts
fs.writeFileSync(path.join(stageDir, 'composer.json'), JSON.stringify(stageComposerJson, null, 4))
run('composer', ['install', '--no-dev', '--no-interaction', '--prefer-dist', '--optimize-autoloader'], stageDir)

// 6. Frontend: built in the real project (real node_modules), then copied into the
// stage. The free entry point never imports frontend/plus/, so its bundle carries no
// Composer UI code; renamed to build/index.tsx.js so the shared PHP (AdminPageModule)
// references the same build output path regardless of edition.
const wpScripts = path.join(root, 'node_modules', '.bin', 'wp-scripts')
const frontendEntry = flavor === 'free' ? 'frontend/index-free.tsx' : 'frontend/index.tsx'
run(wpScripts, ['build', frontendEntry], root)
fs.mkdirSync(path.join(stageDir, 'build'), { recursive: true })
const builtBasename = path.basename(frontendEntry)
fs.copyFileSync(
  path.join(root, 'build', `${builtBasename}.js`),
  path.join(stageDir, 'build', 'index.tsx.js'),
)
fs.copyFileSync(
  path.join(root, 'build', `${builtBasename}.asset.php`),
  path.join(stageDir, 'build', 'index.tsx.asset.php'),
)

// 7. assets/ (logo etc.), generated by the `prebuild` script into the real project dir.
fs.cpSync(path.join(root, 'assets'), path.join(stageDir, 'assets'), { recursive: true })

// 8. package.json driving `wp-scripts plugin-zip` (zip name + root folder = "name" field,
// file list = "files" field). Mirrors the old prepack/postpack package.json renaming
// dance, but scoped to the stage instead of mutating the real package.json in place.
const zipName = flavor === 'plus' ? 'loopress-plus' : 'loopress'
fs.writeFileSync(
  path.join(stageDir, 'package.json'),
  JSON.stringify(
    {
      name: zipName,
      version: pkg.version,
      files: [
        'assets',
        'build',
        'src',
        'vendor',
        'composer.json',
        'loopress.php',
        'readme.txt',
        ...(flavor === 'plus' ? ['uninstall.php'] : []),
      ],
    },
    null,
    4,
  ),
)

// 9. Zip, then move it next to the other build artifacts at the project root (where CI
// and the release workflow expect it).
run(wpScripts, ['plugin-zip'], stageDir)
fs.copyFileSync(path.join(stageDir, `${zipName}.zip`), path.join(root, `${zipName}.zip`))

console.log(`\n${zipName}.zip ready at ${path.join(root, `${zipName}.zip`)}`)
