import {confirm} from '@inquirer/prompts'
import {existsSync, mkdtempSync, readdirSync, rmSync} from 'node:fs'
import {tmpdir} from 'node:os'
import {join} from 'node:path'
import {stripVTControlCharacters} from 'node:util'
import {afterEach, beforeEach, describe, expect, it, vi} from 'vitest'

import Rollback from '../../../src/commands/snippet/rollback.js'
import {type LoopressCommand} from '../../../src/lib/base.js'
import {type CommandClass} from '../../../src/lib/php-files-command.js'
import {type RollbackResult} from '../../../src/lib/rollback-command.js'
import {writeSnapshot} from '../../../src/lib/snapshot-store.js'
import {type EnvironmentConfig} from '../../../src/types/config.js'
import {fakeOclifConfig, resetFakeOclifConfig, silenceLogs} from '../../helpers/oclif.js'
import {makeEnv} from '../../helpers/project-fixtures.js'

vi.mock('@inquirer/prompts', () => ({
  confirm: vi.fn(),
}))

// Tests run without a TTY; same convention as test/lib/push-command.test.ts.
const interactive = vi.hoisted(() => ({value: false}))
vi.mock('../../../src/lib/interactive.js', () => ({
  isInteractive: () => interactive.value,
}))

let rootDir: string

// Snapshot ids are millisecond timestamps; the `--to` test needs two distinct ones.
async function wait(ms: number): Promise<void> {
  await new Promise<void>((resolve) => {
    setTimeout(resolve, ms)
  })
}

// Same as snippet/diff.test.ts: the factory is typed as the abstract base.
const ConcreteRollback = Rollback as unknown as CommandClass<Omit<LoopressCommand, 'run'> & {run(): Promise<RollbackResult>}>

class TestRollback extends ConcreteRollback {
  setup(siteConfig: EnvironmentConfig, options: {dryRun?: boolean; yes?: boolean} = {}) {
    Object.assign(this, {dryRun: options.dryRun ?? false, localConfig: {rootDir}, siteConfig, yes: options.yes ?? false})
  }
}

// The canonical (resource-state.ts) shape of a snippet: no `id` (that's the Map key) and no
// `description` (always regenerated by push, never part of the tracked state).
function canonical(overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    active: true,
    code: 'return 1;',
    insertMethod: 'auto',
    location: 'everywhere',
    name: 'Hero',
    priority: 10,
    shortcodeAttributes: [],
    tags: [],
    type: 'php',
    ...overrides,
  }
}

// The raw REST shape the `loopress/v1/snippets` endpoint returns, i.e. what `snippet remote()`
// normalizes down to `canonical()`.
function remoteRow(id: number, overrides: Partial<Record<string, unknown>> = {}): Record<string, unknown> {
  return {
    active: true,
    code: 'return 1;',
    description: '',
    id,
    insertMethod: 'auto',
    location: 'everywhere',
    name: 'Hero',
    priority: 10,
    shortcodeAttributes: [],
    tags: [],
    type: 'php',
    ...overrides,
  }
}

function make(
  argv: string[],
  get: ReturnType<typeof vi.fn>,
  options: {dryRun?: boolean; siteConfig?: EnvironmentConfig; yes?: boolean} = {},
) {
  const cmd = new TestRollback(argv, fakeOclifConfig)
  cmd.setup(options.siteConfig ?? makeEnv('staging', 'https://staging.acme.com'), {dryRun: options.dryRun, yes: options.yes})
  const logs = silenceLogs(cmd)
  ;(cmd as unknown as {wpClient: unknown}).wpClient = {get}
  return {cmd, logs}
}

describe('snippet rollback', () => {
  beforeEach(() => {
    rootDir = mkdtempSync(join(tmpdir(), 'lps-rollback-cmd-'))
    resetFakeOclifConfig()
    vi.clearAllMocks()
    interactive.value = false
  })

  afterEach(() => {
    rmSync(rootDir, {force: true, recursive: true})
  })

  it('--list reports the available snapshots without touching WordPress', async () => {
    await writeSnapshot({afterState: new Map(), beforeState: new Map(), environment: 'staging', resource: 'snippet', rootDir})
    const get = vi.fn()
    const {cmd} = make(['--list'], get)

    const result = await cmd.run()

    expect(result.status).toBe('listed')
    expect(result.snapshots).toHaveLength(1)
    expect(get).not.toHaveBeenCalled()
    expect(fakeOclifConfig.runCommand).not.toHaveBeenCalled()
  })

  it('--list reports no snapshots for a resource that has never been pushed', async () => {
    const {cmd} = make(['--list'], vi.fn())

    const result = await cmd.run()

    expect(result.snapshots).toEqual([])
  })

  it('rejects when there is no snapshot to roll back to', async () => {
    const {cmd} = make([], vi.fn())

    await expect(cmd.run()).rejects.toThrow(/No snapshots found for "snippet"/)
  })

  it('rolls back to the most recent snapshot when the environment has not moved since that push', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical({name: 'New name'})]]),
      beforeState: new Map([['7', canonical({name: 'Old name'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    // Current remote state matches `afterState`: nothing else has touched it since the push.
    const get = vi.fn(async () => [remoteRow(7, {name: 'New name'})])
    let materializedFiles: string[] = []
    vi.mocked(fakeOclifConfig.runCommand).mockImplementation(async (_id, argv) => {
      const dir = argv![0]
      materializedFiles = readdirSync(dir)
      return {}
    })
    const {cmd} = make([], get)

    const result = await cmd.run()

    expect(result.status).toBe('success')
    expect(fakeOclifConfig.runCommand).toHaveBeenCalledTimes(1)
    const [commandId, argv] = vi.mocked(fakeOclifConfig.runCommand).mock.calls[0]
    expect(commandId).toBe('snippet:push')
    expect(argv).toEqual([expect.any(String), '--env', 'staging', '--yes'])
    // The temp dir materialized the old, pre-push name.
    expect(materializedFiles.some((file) => file.includes('old-name'))).toBe(true)
  })

  it('only materializes and pushes items that actually differ, not every item the snapshot happens to carry', async () => {
    // id 9 is unrelated: present, unchanged, in both the snapshot and the current environment
    // (some other snippet that already existed at push time and was never touched by it). A
    // rollback must never re-push it, an unrelated failure to round-trip it would otherwise
    // fail the whole rollback even though the one item that actually needs restoring is fine.
    await writeSnapshot({
      afterState: new Map([
        ['7', canonical({name: 'New name'})],
        ['9', canonical({name: 'Unrelated', type: 'js'})],
      ]),
      beforeState: new Map([
        ['7', canonical({name: 'Old name'})],
        ['9', canonical({name: 'Unrelated', type: 'js'})],
      ]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7, {name: 'New name'}), remoteRow(9, {name: 'Unrelated', type: 'js'})])
    let materializedFiles: string[] = []
    vi.mocked(fakeOclifConfig.runCommand).mockImplementation(async (_id, argv) => {
      materializedFiles = readdirSync(argv![0])
      return {}
    })
    const {cmd} = make([], get)

    const result = await cmd.run()

    expect(result.status).toBe('success')
    expect(materializedFiles.some((file) => file.includes('old-name'))).toBe(true)
    expect(materializedFiles.some((file) => file.includes('unrelated'))).toBe(false)
  })

  it('cleans up the temp directory used to materialize the snapshot', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical({name: 'Restored'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7)])
    let capturedDir = ''
    vi.mocked(fakeOclifConfig.runCommand).mockImplementation(async (_id, argv) => {
      capturedDir = argv![0]
      expect(existsSync(capturedDir)).toBe(true)
      return {}
    })
    const {cmd} = make([], get)

    await cmd.run()

    expect(existsSync(capturedDir)).toBe(false)
  })

  it('reports no-op and never touches WordPress when the environment already matches the snapshot', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical()]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7)])
    const {cmd} = make([], get)

    const result = await cmd.run()

    expect(result.status).toBe('no-op')
    expect(fakeOclifConfig.runCommand).not.toHaveBeenCalled()
  })

  it('rejects a rollback when the environment drifted since the push, without --yes, non-interactively', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical({name: 'Expected after push'})]]),
      beforeState: new Map([['7', canonical({name: 'Before push'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    // Current remote no longer matches `afterState`: someone changed it after the push.
    const get = vi.fn(async () => [remoteRow(7, {name: 'Changed by someone else'})])
    const {cmd} = make([], get)

    await expect(cmd.run()).rejects.toThrow(
      'The environment has changed since this snapshot was taken. Re-run with --yes to roll back anyway (overwriting those later changes).',
    )
    expect(fakeOclifConfig.runCommand).not.toHaveBeenCalled()
  })

  it('rolls back despite drift when --yes is passed', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical({name: 'Expected after push'})]]),
      beforeState: new Map([['7', canonical({name: 'Before push'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7, {name: 'Changed by someone else'})])
    vi.mocked(fakeOclifConfig.runCommand).mockResolvedValue({})
    const {cmd} = make(['--yes'], get, {yes: true})

    const result = await cmd.run()

    expect(result.status).toBe('success')
    expect(fakeOclifConfig.runCommand).toHaveBeenCalledTimes(1)
  })

  it('--dry-run previews the restore without pushing', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical({name: 'Restored'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7)])
    const {cmd} = make([], get, {dryRun: true})

    const result = await cmd.run()

    expect(result.status).toBe('dry-run')
    expect(result.restored?.changed).toEqual(['7'])
    expect(fakeOclifConfig.runCommand).not.toHaveBeenCalled()
  })

  it('rejects a production rollback without --yes, non-interactively', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical({name: 'Restored'})]]),
      environment: 'production',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7)])
    const {cmd} = make([], get, {siteConfig: makeEnv('production', 'https://acme.com')})

    await expect(cmd.run()).rejects.toThrow(/production/)
    expect(fakeOclifConfig.runCommand).not.toHaveBeenCalled()
  })

  it('--to restores a specific, older snapshot instead of the most recent one', async () => {
    const older = await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical({name: 'From the older snapshot'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    await wait(2)
    await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical({name: 'From the newest snapshot'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7)])
    let materializedFiles: string[] = []
    vi.mocked(fakeOclifConfig.runCommand).mockImplementation(async (_id, argv) => {
      const dir = argv![0]
      materializedFiles = readdirSync(dir)
      return {}
    })
    const {cmd} = make(['--to', older], get)

    const result = await cmd.run()

    expect(result.id).toBe(older)
    expect(materializedFiles.some((file) => file.includes('from-the-older-snapshot'))).toBe(true)
  })

  it('includes the drift in the structured result, not just the log, so a JSON/MCP caller can see it before confirming', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical({name: 'Expected after push'})]]),
      beforeState: new Map([['7', canonical({name: 'Before push'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7, {name: 'Changed by someone else'})])
    vi.mocked(fakeOclifConfig.runCommand).mockResolvedValue({})
    const {cmd} = make(['--yes'], get, {yes: true})

    const result = await cmd.run()

    expect(result.drift?.changed).toEqual(['7'])
  })

  it('has no drift field when the environment matches what the push expected to leave behind', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical({name: 'New name'})]]),
      beforeState: new Map([['7', canonical({name: 'Old name'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7, {name: 'New name'})])
    vi.mocked(fakeOclifConfig.runCommand).mockResolvedValue({})
    const {cmd} = make([], get)

    const result = await cmd.run()

    expect(result.drift).toBeUndefined()
  })

  it('warns that an item absent from the snapshot will not be removed, since restoring only creates and updates', async () => {
    await writeSnapshot({
      afterState: new Map([
        ['7', canonical()],
        ['9', canonical({name: 'Added after the push'})],
      ]),
      beforeState: new Map([['7', canonical()]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const get = vi.fn(async () => [remoteRow(7), remoteRow(9, {name: 'Added after the push'})])
    vi.mocked(fakeOclifConfig.runCommand).mockResolvedValue({})
    const {cmd, logs} = make([], get)

    await cmd.run()

    expect(logs.warn).toHaveBeenCalledWith(expect.stringContaining('will NOT be removed'))
  })

  it('scopes snapshots by environment: a production rollback never sees a staging snapshot', async () => {
    await writeSnapshot({
      afterState: new Map([['7', canonical()]]),
      beforeState: new Map([['7', canonical({name: 'Staging restore point'})]]),
      environment: 'staging',
      resource: 'snippet',
      rootDir,
    })
    const {cmd} = make([], vi.fn(), {siteConfig: makeEnv('production', 'https://acme.com')})

    await expect(cmd.run()).rejects.toThrow(/No snapshots found for "snippet" on "production"/)
  })

  describe('human output', () => {
    // Colors depend on the terminal; only the text is under test.
    function lines(logs: ReturnType<typeof silenceLogs>): string[] {
      return logs.log.mock.calls.map(([line]) => stripVTControlCharacters(String(line)))
    }

    it('--list prints each snapshot id and date, most recent first', async () => {
      const id = await writeSnapshot({afterState: new Map(), beforeState: new Map(), environment: 'staging', resource: 'snippet', rootDir})
      const {cmd, logs} = make(['--list'], vi.fn())

      const result = await cmd.run()

      expect(lines(logs)).toEqual([
        'Snapshots for "snippet" on "staging" (most recent first):',
        `  ${id}  ${result.snapshots![0].createdAt}`,
      ])
    })

    it('--list explains where snapshots come from when there are none', async () => {
      const {cmd, logs} = make(['--list'], vi.fn())

      await cmd.run()

      expect(lines(logs)).toEqual([
        'No snapshots found for "snippet" on "staging". A snapshot is written automatically by `lps snippet push`.',
      ])
    })

    it('--list prints nothing under --json', async () => {
      await writeSnapshot({afterState: new Map(), beforeState: new Map(), environment: 'staging', resource: 'snippet', rootDir})
      const {cmd, logs} = make(['--list', '--json'], vi.fn())

      await cmd.run()

      expect(logs.log).not.toHaveBeenCalled()
    })

    it('prints the drift and the restore plan, then confirms the rollback', async () => {
      const id = await writeSnapshot({
        afterState: new Map([
          ['7', canonical({name: 'Expected after push'})],
          ['8', canonical({name: 'Gone'})],
        ]),
        beforeState: new Map([['7', canonical({name: 'Before push'})]]),
        environment: 'staging',
        resource: 'snippet',
        rootDir,
      })
      const get = vi.fn(async () => [remoteRow(7, {name: 'Changed by someone else'}), remoteRow(9, {name: 'New'})])
      vi.mocked(fakeOclifConfig.runCommand).mockResolvedValue({})
      const {cmd, logs} = make(['--yes'], get, {yes: true})

      await cmd.run()
      const output = lines(logs)

      expect(output[0]).toMatch(new RegExp(String.raw`^Rolling back Snippets on https://staging\.acme\.com to the snapshot from \S+ \(${id}\)$`))
      expect(output).toContain('Snippets has changed on https://staging.acme.com since that push:')
      expect(output).toContain('  + 9')
      expect(output).toContain('  - 8')
      expect(output).toContain('  ~ 7')
      expect(output).toContain('This would restore Snippets to:')
      expect(output.at(-1)).toMatch(/^Rolled back Snippets to the snapshot from \S+\.$/)
      // A patch line is indented under its "~ id" header, blank lines are left empty.
      const patch = output[output.indexOf('  ~ 7') + 1]
      expect(patch.split('\n').every((line) => line === '' || line.startsWith(' '.repeat(4)))).toBe(true)
      expect(patch).toBe(patch.trimEnd())
    })

    it('prints no diff under --json', async () => {
      await writeSnapshot({
        afterState: new Map([['7', canonical()]]),
        beforeState: new Map([['7', canonical({name: 'Restored'})]]),
        environment: 'staging',
        resource: 'snippet',
        rootDir,
      })
      const {cmd, logs} = make(['--json'], vi.fn(async () => [remoteRow(7)]), {dryRun: true})

      await cmd.run()

      expect(lines(logs).some((line) => line.startsWith('This would restore'))).toBe(false)
    })

    it('says so when there is nothing to restore', async () => {
      await writeSnapshot({afterState: new Map([['7', canonical()]]), beforeState: new Map([['7', canonical()]]), environment: 'staging', resource: 'snippet', rootDir})
      const {cmd, logs} = make([], vi.fn(async () => [remoteRow(7)]))

      await cmd.run()

      expect(lines(logs)).toContain('Nothing to restore, the environment already matches this snapshot.')
    })

    it('names a single item that will not be removed, and refers to it as "it"', async () => {
      await writeSnapshot({
        afterState: new Map([
          ['7', canonical()],
          ['9', canonical({name: 'Added after the push'})],
        ]),
        beforeState: new Map([['7', canonical()]]),
        environment: 'staging',
        resource: 'snippet',
        rootDir,
      })
      const get = vi.fn(async () => [remoteRow(7), remoteRow(9, {name: 'Added after the push'})])
      const {cmd, logs} = make([], get, {dryRun: true})

      await cmd.run()

      expect(logs.warn).toHaveBeenCalledWith(
        '1 item present now but not in this snapshot will NOT be removed (9): restoring only creates and updates, the same as `lps snippet push`. Remove it by hand if that\'s part of undoing the original push.',
      )
    })

    it('refers to several items that will not be removed as "them"', async () => {
      await writeSnapshot({
        afterState: new Map([
          ['7', canonical()],
          ['8', canonical({name: 'A'})],
          ['9', canonical({name: 'B'})],
        ]),
        beforeState: new Map([['7', canonical()]]),
        environment: 'staging',
        resource: 'snippet',
        rootDir,
      })
      const get = vi.fn(async () => [remoteRow(7), remoteRow(8, {name: 'A'}), remoteRow(9, {name: 'B'})])
      const {cmd, logs} = make([], get, {dryRun: true})

      await cmd.run()

      expect(logs.warn).toHaveBeenCalledWith(expect.stringMatching(/^2 items present now .* \(8, 9\): .* Remove them by hand/))
    })
  })

  describe('interactive drift confirmation', () => {
    async function driftedSnapshot(): Promise<void> {
      await writeSnapshot({
        afterState: new Map([['7', canonical({name: 'Expected after push'})]]),
        beforeState: new Map([['7', canonical({name: 'Before push'})]]),
        environment: 'staging',
        resource: 'snippet',
        rootDir,
      })
    }

    it('asks in a TTY and rolls back when accepted', async () => {
      interactive.value = true
      vi.mocked(confirm).mockResolvedValueOnce(true)
      vi.mocked(fakeOclifConfig.runCommand).mockResolvedValue({})
      await driftedSnapshot()
      const {cmd} = make([], vi.fn(async () => [remoteRow(7, {name: 'Changed'})]))

      const result = await cmd.run()

      expect(confirm).toHaveBeenCalledWith({
        default: false,
        message: 'The environment has changed since this snapshot was taken. Roll back anyway, overwriting those later changes?',
      })
      expect(result.status).toBe('success')
    })

    it('asks in a TTY and aborts when declined', async () => {
      interactive.value = true
      vi.mocked(confirm).mockResolvedValueOnce(false)
      await driftedSnapshot()
      const {cmd} = make([], vi.fn(async () => [remoteRow(7, {name: 'Changed'})]))

      await expect(cmd.run()).rejects.toThrow('Aborted.')
      expect(fakeOclifConfig.runCommand).not.toHaveBeenCalled()
    })

    it('never asks on a dry run', async () => {
      interactive.value = true
      await driftedSnapshot()
      const {cmd} = make([], vi.fn(async () => [remoteRow(7, {name: 'Changed'})]), {dryRun: true})

      const result = await cmd.run()

      expect(confirm).not.toHaveBeenCalled()
      expect(result.status).toBe('dry-run')
    })
  })
})
